[package]
name = "advent_of_code_traits"
version = "0.1.0"
authors = ["drmason13 <drmason13@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[[example]]
name = "without_parsing"
crate-type = ["staticlib"]

[[example]]
name = "parse_each_input"
crate-type = ["staticlib"]
